"""initial schema

Revision ID: 28573de58cb1
Revises: 
Create Date: 2026-09-28 01:45:38.957223

"""
from alembic import op
import sqlalchemy as sa

import app.core.db
from app.cli import LANGUAGES


# revision identifiers, used by Alembic.
revision = '28573de58cb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('native_name', sa.String(length=64), nullable=False),
    sa.Column('is_rtl', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_languages'))
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('native_language_code', sa.String(length=8), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('daily_new_limit', sa.Integer(), nullable=False),
    sa.Column('daily_review_limit', sa.Integer(), nullable=False),
    sa.Column('daily_goal', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', app.core.db.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('collections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=10), nullable=False),
    sa.Column('system_key', sa.String(length=20), nullable=True),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('language_code', sa.String(length=8), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_collections_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['collections.id'], name=op.f('fk_collections_parent_id_collections'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collections')),
    sa.UniqueConstraint('share_token', name=op.f('uq_collections_share_token'))
    )
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collections_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collections_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index('ix_collections_visibility', ['visibility'], unique=False)

    op.create_table('daily_activity',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('reviews', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('new_learned', sa.Integer(), nullable=False),
    sa.Column('time_spent_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_daily_activity_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'local_date', name=op.f('pk_daily_activity'))
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('revoked_at', app.core.db.UTCDateTime(), nullable=True),
    sa.Column('replaced_by_jti', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('jti', name=op.f('uq_refresh_tokens_jti'))
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_sources_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources'))
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index('ix_sources_owner_title', ['owner_id', 'title'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_tags_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('owner_id', 'name', name=op.f('uq_tags_owner_id_name'))
    )
    op.create_table('vocabularies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('language_code', sa.String(length=8), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=False),
    sa.Column('normalized_text', sa.String(length=200), nullable=False),
    sa.Column('phonetic', sa.String(length=200), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('difficulty', sa.String(length=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('enrichment_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], name=op.f('fk_vocabularies_language_code_languages')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_vocabularies_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vocabularies')),
    sa.UniqueConstraint('owner_id', 'language_code', 'normalized_text', name=op.f('uq_vocabularies_owner_id_language_code_normalized_text'))
    )
    with op.batch_alter_table('vocabularies', schema=None) as batch_op:
        batch_op.create_index('ix_vocabularies_owner_created', ['owner_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vocabularies_owner_id'), ['owner_id'], unique=False)

    op.create_table('card_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('vocabulary_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('due_at', app.core.db.UTCDateTime(), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('wrong_count', sa.Integer(), nullable=False),
    sa.Column('first_reviewed_at', app.core.db.UTCDateTime(), nullable=True),
    sa.Column('last_reviewed_at', app.core.db.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_card_progress_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabularies.id'], name=op.f('fk_card_progress_vocabulary_id_vocabularies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card_progress')),
    sa.UniqueConstraint('user_id', 'vocabulary_id', name=op.f('uq_card_progress_user_id_vocabulary_id'))
    )
    with op.batch_alter_table('card_progress', schema=None) as batch_op:
        batch_op.create_index('ix_card_progress_user_due', ['user_id', 'due_at'], unique=False)
        batch_op.create_index('ix_card_progress_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_progress_vocabulary_id'), ['vocabulary_id'], unique=False)

    op.create_table('collection_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('collection_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('is_learning', sa.Boolean(), nullable=False),
    sa.Column('joined_at', app.core.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_collection_members_collection_id_collections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_collection_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_members')),
    sa.UniqueConstraint('collection_id', 'user_id', name=op.f('uq_collection_members_collection_id_user_id'))
    )
    with op.batch_alter_table('collection_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_members_user_id'), ['user_id'], unique=False)

    op.create_table('collection_words',
    sa.Column('collection_id', sa.String(length=36), nullable=False),
    sa.Column('vocabulary_id', sa.String(length=36), nullable=False),
    sa.Column('added_by', sa.String(length=36), nullable=True),
    sa.Column('added_at', app.core.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_collection_words_added_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_collection_words_collection_id_collections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabularies.id'], name=op.f('fk_collection_words_vocabulary_id_vocabularies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'vocabulary_id', name=op.f('pk_collection_words'))
    )
    with op.batch_alter_table('collection_words', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_words_vocabulary_id'), ['vocabulary_id'], unique=False)

    op.create_table('external_applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_collection_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['default_collection_id'], ['collections.id'], name=op.f('fk_external_applications_default_collection_id_collections'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_external_applications_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_applications'))
    )
    with op.batch_alter_table('external_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_applications_owner_id'), ['owner_id'], unique=False)

    op.create_table('media_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vocabulary_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabularies.id'], name=op.f('fk_media_assets_vocabulary_id_vocabularies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_assets'))
    )
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_assets_vocabulary_id'), ['vocabulary_id'], unique=False)

    op.create_table('vocabulary_contexts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vocabulary_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('sentence', sa.Text(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('captured_via', sa.String(length=64), nullable=True),
    sa.Column('captured_at', app.core.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_vocabulary_contexts_source_id_sources'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabularies.id'], name=op.f('fk_vocabulary_contexts_vocabulary_id_vocabularies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vocabulary_contexts'))
    )
    with op.batch_alter_table('vocabulary_contexts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vocabulary_contexts_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vocabulary_contexts_vocabulary_id'), ['vocabulary_id'], unique=False)

    op.create_table('vocabulary_senses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('vocabulary_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('part_of_speech', sa.String(length=30), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('translation_language_code', sa.String(length=8), nullable=True),
    sa.Column('synonyms', sa.JSON(), nullable=False),
    sa.Column('antonyms', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabularies.id'], name=op.f('fk_vocabulary_senses_vocabulary_id_vocabularies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vocabulary_senses'))
    )
    with op.batch_alter_table('vocabulary_senses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vocabulary_senses_vocabulary_id'), ['vocabulary_id'], unique=False)

    op.create_table('vocabulary_tags',
    sa.Column('vocabulary_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_vocabulary_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabularies.id'], name=op.f('fk_vocabulary_tags_vocabulary_id_vocabularies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vocabulary_id', 'tag_id', name=op.f('pk_vocabulary_tags'))
    )
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('last_used_at', app.core.db.UTCDateTime(), nullable=True),
    sa.Column('expires_at', app.core.db.UTCDateTime(), nullable=True),
    sa.Column('revoked_at', app.core.db.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['external_applications.id'], name=op.f('fk_api_keys_application_id_external_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_keys_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('prefix', name=op.f('uq_api_keys_prefix'))
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_user_id'), ['user_id'], unique=False)

    op.create_table('review_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('card_progress_id', sa.String(length=36), nullable=False),
    sa.Column('vocabulary_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=12), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('verdict', sa.String(length=10), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('response_ms', sa.Integer(), nullable=True),
    sa.Column('prev_state', sa.JSON(), nullable=False),
    sa.Column('new_interval_days', sa.Integer(), nullable=False),
    sa.Column('new_ease_factor', sa.Float(), nullable=False),
    sa.Column('new_due_at', app.core.db.UTCDateTime(), nullable=True),
    sa.Column('client_review_id', sa.String(length=64), nullable=True),
    sa.Column('reviewed_at', app.core.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_progress_id'], ['card_progress.id'], name=op.f('fk_review_logs_card_progress_id_card_progress'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_review_logs_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabularies.id'], name=op.f('fk_review_logs_vocabulary_id_vocabularies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_logs')),
    sa.UniqueConstraint('user_id', 'client_review_id', name=op.f('uq_review_logs_user_id_client_review_id'))
    )
    with op.batch_alter_table('review_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_logs_card_progress_id'), ['card_progress_id'], unique=False)
        batch_op.create_index('ix_review_logs_user_time', ['user_id', 'reviewed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_logs_vocabulary_id'), ['vocabulary_id'], unique=False)

    op.create_table('vocabulary_examples',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sense_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('sentence', sa.Text(), nullable=False),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sense_id'], ['vocabulary_senses.id'], name=op.f('fk_vocabulary_examples_sense_id_vocabulary_senses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vocabulary_examples'))
    )
    with op.batch_alter_table('vocabulary_examples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vocabulary_examples_sense_id'), ['sense_id'], unique=False)

    # ### end Alembic commands ###

    languages = sa.table(
        "languages",
        sa.column("code", sa.String),
        sa.column("name", sa.String),
        sa.column("native_name", sa.String),
        sa.column("is_rtl", sa.Boolean),
    )
    op.bulk_insert(
        languages,
        [{"code": c, "name": n, "native_name": nn, "is_rtl": rtl} for c, n, nn, rtl in LANGUAGES],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocabulary_examples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocabulary_examples_sense_id'))

    op.drop_table('vocabulary_examples')
    with op.batch_alter_table('review_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_logs_vocabulary_id'))
        batch_op.drop_index('ix_review_logs_user_time')
        batch_op.drop_index(batch_op.f('ix_review_logs_card_progress_id'))

    op.drop_table('review_logs')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_application_id'))

    op.drop_table('api_keys')
    op.drop_table('vocabulary_tags')
    with op.batch_alter_table('vocabulary_senses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocabulary_senses_vocabulary_id'))

    op.drop_table('vocabulary_senses')
    with op.batch_alter_table('vocabulary_contexts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocabulary_contexts_vocabulary_id'))
        batch_op.drop_index(batch_op.f('ix_vocabulary_contexts_source_id'))

    op.drop_table('vocabulary_contexts')
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_assets_vocabulary_id'))

    op.drop_table('media_assets')
    with op.batch_alter_table('external_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_applications_owner_id'))

    op.drop_table('external_applications')
    with op.batch_alter_table('collection_words', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_words_vocabulary_id'))

    op.drop_table('collection_words')
    with op.batch_alter_table('collection_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_members_user_id'))

    op.drop_table('collection_members')
    with op.batch_alter_table('card_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_progress_vocabulary_id'))
        batch_op.drop_index('ix_card_progress_user_status')
        batch_op.drop_index('ix_card_progress_user_due')

    op.drop_table('card_progress')
    with op.batch_alter_table('vocabularies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocabularies_owner_id'))
        batch_op.drop_index('ix_vocabularies_owner_created')

    op.drop_table('vocabularies')
    op.drop_table('tags')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index('ix_sources_owner_title')

    op.drop_table('sources')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_family_id'))

    op.drop_table('refresh_tokens')
    op.drop_table('daily_activity')
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_index('ix_collections_visibility')
        batch_op.drop_index(batch_op.f('ix_collections_parent_id'))
        batch_op.drop_index(batch_op.f('ix_collections_owner_id'))

    op.drop_table('collections')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('languages')
    # ### end Alembic commands ###
