"""study plans per collection

Words are only scheduled through a started collection (study plan). To keep
existing learners' progress flowing, this migration:
  1. puts every word that is in none of its owner's collections into the owner's Inbox;
  2. creates an active plan for each (user, collection) where the user has already
     started at least one word of that collection.

Revision ID: 87c8a28876b1
Revises: 28573de58cb1
Create Date: 2026-09-28 10:56:59.376367

"""
import uuid
from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa

import app.core.db


# revision identifiers, used by Alembic.
revision = '87c8a28876b1'
down_revision = '28573de58cb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('collection_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('new_per_day', sa.Integer(), nullable=False),
    sa.Column('started_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('paused_at', app.core.db.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.core.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_study_plans_collection_id_collections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_study_plans_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_study_plans')),
    sa.UniqueConstraint('user_id', 'collection_id', name=op.f('uq_study_plans_user_id_collection_id'))
    )
    with op.batch_alter_table('study_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_plans_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_plans_user_id'), ['user_id'], unique=False)

    _migrate_data()

    with op.batch_alter_table('collection_members', schema=None) as batch_op:
        batch_op.drop_column('is_learning')

    # ### end Alembic commands ###


def _migrate_data():
    bind = op.get_bind()
    bind.execute(sa.text("""
        INSERT INTO collection_words (collection_id, vocabulary_id, added_by, added_at)
        SELECT inbox.id, v.id, v.owner_id, v.created_at
        FROM vocabularies v
        JOIN collections inbox ON inbox.owner_id = v.owner_id AND inbox.system_key = 'inbox'
        WHERE NOT EXISTS (
            SELECT 1 FROM collection_words cw JOIN collections c ON c.id = cw.collection_id
            WHERE cw.vocabulary_id = v.id AND c.owner_id = v.owner_id
        )
    """))
    rows = bind.execute(sa.text("""
        SELECT DISTINCT cp.user_id, cw.collection_id, u.daily_new_limit
        FROM card_progress cp
        JOIN users u ON u.id = cp.user_id
        JOIN collection_words cw ON cw.vocabulary_id = cp.vocabulary_id
        JOIN collections c ON c.id = cw.collection_id
        WHERE cp.status != 'NEW'
          AND (c.owner_id = cp.user_id OR EXISTS (
                SELECT 1 FROM collection_members m WHERE m.collection_id = c.id AND m.user_id = cp.user_id))
    """)).fetchall()
    if not rows:
        return
    now = datetime.now(timezone.utc).replace(tzinfo=None)
    plans = sa.table(
        "study_plans",
        sa.column("id", sa.String), sa.column("user_id", sa.String), sa.column("collection_id", sa.String),
        sa.column("status", sa.String), sa.column("new_per_day", sa.Integer), sa.column("started_at", sa.DateTime),
        sa.column("created_at", sa.DateTime), sa.column("updated_at", sa.DateTime),
    )
    op.bulk_insert(plans, [
        {"id": str(uuid.uuid4()), "user_id": user_id, "collection_id": collection_id, "status": "active",
         "new_per_day": new_per_day if new_per_day is not None else 10,
         "started_at": now, "created_at": now, "updated_at": now}
        for user_id, collection_id, new_per_day in rows
    ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_learning', sa.BOOLEAN(), nullable=False, server_default=sa.true()))

    with op.batch_alter_table('study_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_plans_user_id'))
        batch_op.drop_index(batch_op.f('ix_study_plans_collection_id'))

    op.drop_table('study_plans')
    # ### end Alembic commands ###
